language: php

php:
    - 5.3
    - 5.4
    - 5.5
    
matrix:
    allow_failures:
        - php: 5.5
        
before_script:
    - composer selfupdate
    - composer --dev install
    # set up database
    - mysql -e 'CREATE DATABASE wp_cli_test;' -uroot
    - mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1"' -uroot
    - tests/bin/restore_mysql
    
script:
    - phpunit -c tests --testdox --coverage-text