language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    
matrix:
    allow_failures:
        - php: 5.4
        - php: 5.5
        
services:
    - mysql
before_script:
    # set up database
    - mysql -e 'CREATE DATABASE wp_cli_test;' -uroot
    - mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1"' -uroot    
    - COMPOSER_ROOT_VERSION=dev-master composer selfupdate
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
    
script:
    - phpunit -c tests --testdox